# 02 – Preprocessing & Data Cleaning

### Purpose of the Notebook
This notebook applies systematic cleaning and standardisation to the pre‑saved datasets (dataset.pkl and dataset_de.pkl).
All decisions are based on the insights from Notebook 01_data_overview (EDA), including handling of missing data, removal of low‑quality fields, type corrections, logical consistency checks, and creation of derived features.

### Steps
- Load pre‑saved datasets
- Apply preprocessing pypline
- Save cleaned datasets

--------------
### Load Pre-Saved Dataset

-----------

In [1]:
# ---------------------------------------------------------
# Import moduls
# ---------------------------------------------------------


# import standard modules
import pandas as pd
import numpy as np
from pathlib import Path

import sys
from pathlib import Path

In [2]:
# shut off some annoying warnings
import warnings

warnings.filterwarnings("ignore", message="A value is trying to be set on a copy")
warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

In [3]:
# ---------------------------------------------------------
# Setup style
# ---------------------------------------------------------

# show all columns
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# visualisation settings
pd.set_option('display.float_format', '{:,.2f}'.format)

In [4]:
# ---------------------------------------------------------
# Load scripts
# ----------------------------------------------------------

%load_ext autoreload
%autoreload 2

from pathlib import Path
import sys

# found min directory
PROJECT_ROOT = Path("..").resolve()

# maindirectory sys.path
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# import function from script
from my_scripts.preprocessing import preprocess
from my_scripts.eda import overview

In [5]:
# ---------------------------------------------------------
# Import dataset
# ---------------------------------------------------------

df = pd.read_pickle("../data/dataset.pkl")
df_de = pd.read_pickle("../data/dataset_de.pkl")

print("EU dataset:", df.shape)
print("DE dataset:", df_de.shape)

EU dataset: (4362869, 75)
DE dataset: (309652, 75)

--------------
### Apply preprocessing pipeline
-----------

In [6]:
# ---------------------------------------------------------
# full EU dataset
# ---------------------------------------------------------

df_clean = preprocess(df)

In [7]:
# shape of the cleaned EU dataset
print(df_clean.shape)

(4362869, 30)

In [8]:
# inspekt of the cleaned EU dataset
overview(df_clean)

,dtype,total,missing_n,missing_%,uniques_n,uniques
YEAR,int64,4362869,0,0.00,9,"[2008, 2009, 2010, 2011, 2012, 2013, 2014, 201..."
ID_TYPE,int64,4362869,0,0.00,7,"[3, 6, 18, 25, 21, 23, 22]"
DT_DISPATCH,datetime64[ns],4362869,0,0.00,3297,"[2007-12-11 00:00:00, 2007-12-27 00:00:00, 200..."
XSD_VERSION,object,4362869,0,0.00,7,"[D205, D206, D207, R207.S3, R208.S1, R208.S2, ..."
CANCELLED,int64,4362869,0,0.00,2,"[0, 1]"
CORRECTIONS,int64,4362869,0,0.00,10,"[0, 1, 2, 4, 3, 5, 84, 7, 8, 6]"
ISO_COUNTRY_CODE,object,4362869,0,0.00,33,"[DE, FR, ES, SE, PL, IT, HU, CY, UK, RO, PT, N..."
CAE_TYPE,object,4362869,0,0.00,10,"[8, 3, 6, 1, R, N, 4, 5A, 5, Z]"
B_AWARDED_BY_CENTRAL_BODY,object,4362869,0,0.00,3,"[nan, Y, N]"
TYPE_OF_CONTRACT,object,4362869,0,0.00,3,"[W, U, S]"
TAL_LOCATION_NUTS,object,4362869,0,0.00,9485,"[DED31, DE913, nan, DE13A, ES3, FR91, FR522, F..."
B_DYN_PURCH_SYST,object,4362869,0,0.00,3,"[nan, Y, N]"
CPV,object,4362869,0,0.00,11053,"[45215000.0, 45215100.0, 45421145.0, 45211100...."
ID_LOT,object,4362869,0,0.00,3334,"[nan, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, Zp 2130-6..."
LOTS_NUMBER,float64,4350004,12865,0.29,375,"[0.0, 3.0, 2.0, 1.0, 4.0, 10.0, 7.0, 5.0, 13.0..."
VALUE_EURO,float64,2624436,1738433,39.85,665289,"[nan, 5204457.56, 4924202.16, 1400000.0, 88398..."
B_EU_FUNDS,object,4362869,0,0.00,3,"[nan, N, Y]"
TOP_TYPE,object,4362869,0,0.00,10,"[OPE, NIC, RES, NOC, COD, nan, AWP, NOP, NIP, ..."
B_ACCELERATED,object,4362869,0,0.00,2,"[nan, Y]"
OUT_OF_DIRECTIVES,int64,4362869,0,0.00,2,"[0, 1]"
CRIT_CODE,object,4362869,0,0.00,3,"[M, L, nan]"
B_ELECTRONIC_AUCTION,object,4362869,0,0.00,3,"[N, nan, Y]"
NUMBER_AWARDS,int64,4362869,0,0.00,488,"[1, 3, 6, 7, 19, 4, 2, 11, 5, 18, 9, 12, 10, 5..."
B_AWARDED_TO_A_GROUP,object,4362869,0,0.00,3,"[nan, N, Y]"
WIN_COUNTRY_CODE,object,4362869,0,0.00,710,"[DE, FR, nan, PL, IT, HU, CY, US, UK, RO, AT, ..."
B_CONTRACTOR_SME,object,4362869,0,0.00,413,"[nan, N, Y, N---Y---N---N, N---Y---N, N---Y---..."
NUMBER_OFFERS,float64,3536722,826147,18.94,449,"[2.0, 3.0, 1.0, nan, 6.0, 9.0, 5.0, 45.0, 4.0,..."
AWARD_VALUE_EURO,float64,2861709,1501160,34.41,1692490,"[302964.15, 478780.08, nan, 2255999.0, 2346232..."
B_SUBCONTRACTED,object,4362869,0,0.00,3,"[nan, N, Y]"
DT_AWARD,datetime64[ns],4031149,331720,7.60,4206,"[2007-09-29 00:00:00, 2007-12-21 00:00:00, 200..."

In [9]:
# ---------------------------------------------------------
# dataset for Germany
# ---------------------------------------------------------

df_de_clean = preprocess(df_de)

In [10]:
# shape of the cleaned dataset for Germany
print(df_de_clean.shape)

(309652, 30)

In [11]:
# inspekt of the cleaned dataset  for Germany
overview(df_de_clean)

,dtype,total,missing_n,missing_%,uniques_n,uniques
YEAR,int64,309652,0,0.00,9,"[2008, 2009, 2010, 2011, 2012, 2013, 2014, 201..."
ID_TYPE,int64,309652,0,0.00,5,"[3, 6, 18, 25, 21]"
DT_DISPATCH,datetime64[ns],309652,0,0.00,2805,"[2007-12-11 00:00:00, 2007-12-27 00:00:00, 200..."
XSD_VERSION,object,309652,0,0.00,7,"[D205, D206, D207, R207.S3, R208.S1, R208.S2, ..."
CANCELLED,int64,309652,0,0.00,2,"[0, 1]"
CORRECTIONS,int64,309652,0,0.00,3,"[0, 1, 2]"
ISO_COUNTRY_CODE,object,309652,0,0.00,1,[DE]
CAE_TYPE,object,309652,0,0.00,10,"[8, 3, 6, N, 1, R, 4, 5A, 5, Z]"
B_AWARDED_BY_CENTRAL_BODY,object,309652,0,0.00,3,"[nan, Y, N]"
TYPE_OF_CONTRACT,object,309652,0,0.00,3,"[W, U, S]"
TAL_LOCATION_NUTS,object,309652,0,0.00,2129,"[DED31, DE913, DE13A, DE915, DE712, DEA52, DE9..."
B_DYN_PURCH_SYST,object,309652,0,0.00,3,"[nan, Y, N]"
CPV,object,309652,0,0.00,5668,"[45215000.0, 45215100.0, 45233110.0, 45214600...."
ID_LOT,object,309652,0,0.00,450,"[nan, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, V2, M2, O..."
LOTS_NUMBER,float64,308885,767,0.25,127,"[0.0, 2.0, 3.0, 7.0, 1.0, 11.0, 4.0, 5.0, 8.0,..."
VALUE_EURO,float64,153965,155687,50.28,89797,"[nan, 5204457.56, 16671.43, 105600.0, 1476658...."
B_EU_FUNDS,object,309652,0,0.00,3,"[nan, N, Y]"
TOP_TYPE,object,309652,0,0.00,9,"[OPE, NOC, NIC, RES, nan, COD, AWP, NOP, NIP]"
B_ACCELERATED,object,309652,0,0.00,2,"[nan, Y]"
OUT_OF_DIRECTIVES,int64,309652,0,0.00,2,"[0, 1]"
CRIT_CODE,object,309652,0,0.00,3,"[M, L, nan]"
B_ELECTRONIC_AUCTION,object,309652,0,0.00,3,"[N, nan, Y]"
NUMBER_AWARDS,int64,309652,0,0.00,159,"[1, 2, 3, 4, 6, 5, 0, 19, 8, 13, 7, 9, 14, 12,..."
B_AWARDED_TO_A_GROUP,object,309652,0,0.00,3,"[nan, N, Y]"
WIN_COUNTRY_CODE,object,309652,0,0.00,118,"[DE, nan, EE, UK, FR, FI, JO, LB, CH, ES, AT, ..."
B_CONTRACTOR_SME,object,309652,0,0.00,25,"[nan, N, Y, Y---Y, N---N---N, N---N, Y---Y---Y..."
NUMBER_OFFERS,float64,257847,51805,16.73,146,"[2.0, 3.0, 9.0, 5.0, 10.0, 19.0, 8.0, nan, 1.0..."
AWARD_VALUE_EURO,float64,150932,158720,51.26,128064,"[302964.15, 478780.08, nan, 478516.22, 129470...."
B_SUBCONTRACTED,object,309652,0,0.00,3,"[nan, N, Y]"
DT_AWARD,datetime64[ns],280161,29491,9.52,3484,"[2007-09-29 00:00:00, 2007-12-21 00:00:00, 200..."

#### Notes: Summary of Data Cleaning Results

1. Dataset Size After Preprocessing
- Full EU dataset:
  - Before: 4,362,869 rows × 75 columns
  - After: 4,362,869 rows × 30 columns

- Germany-only dataset:
  - Before: 309,652 rows × 75 columns
  - After: 309,652 rows × 30 columns

2. The reduction from 75 to 30 columns is the result of removing:
- Columns removed due to >40% missing values
  - Winner information (WIN_*)
  - Contracting authority details (CAE_*)
  - GPA-related fields
  - Secondary financial fields (VALUE_EURO_FIN_*, AWARD_VALUE_EURO_FIN_1)
  - Award criteria weights (CRIT_*)
  - Additional CPVs
  - High-cardinality procedural flags (B_MULTIPLE_, B_FRA_, FRA_ESTIMATED, etc.)
  - TED_NOTICE_URL

- Columns removed due to irrelevance for competition modelling
  - Identifiers (ID_NOTICE_CAN, ID_AWARD, ID_LOT_AWARDED, CONTRACT_NUMBER)
  - Textual descriptions (TITLE)
  - Non-award information (INFO_ON_NON_AWARD, INFO_UNPUBLISHED)
  - Administrative metadata (MAIN_ACTIVITY, EU_INST_CODE)

3. Key Variables Retained Despite Missing Values
Several columns with substantial missingness were intentionally retained because they are critical for modelling tender competition and failure risk:
- VALUE_EURO
  - Missing: 39.85% (EU dataset)
  - Missing: 50.28% (Germany)
  - Importance: baseline contract value, used for log-transformations and value bins.

- AWARD_VALUE_EURO
  - Missing: 34.41% (EU dataset)
  - Missing: 51.26% (Germany)
  - Importance: actual awarded value, essential for understanding tender dynamics.

- NUMBER_OFFERS
  - Missing: 18.94% (EU dataset)
  - Missing: 16.73% (Germany)
  - Importance: primary target variable for defining failed / low-competition tenders.

These variables were not removed because:
They are central to the analytical goal (competition modelling).
Missingness is informative, not random.

4. Additional Preprocessing Steps
- All categorical missing values were replaced with "Unknown".
- Numeric missing values were left as NaN, to be handled during modelling.

5. Conversion of Categorical Variables
To ensure correct feature engineering and avoid dtype-related errors, all categorical variables were explicitly converted to string (object).
This includes fields such as:
  - ISO_COUNTRY_CODE
  - CAE_TYPE
  - TYPE_OF_CONTRACT
  - TAL_LOCATION_NUTS
  - B_EU_FUNDS
  - TOP_TYPE
  - CRIT_CODE
  - B_ELECTRONIC_AUCTION
  - B_AWARDED_TO_A_GROUP
  - WIN_COUNTRY_CODE
  - B_CONTRACTOR_SME
  - B_SUBCONTRACTED
  - CPV (converted from float → string, with removal of “.0”)
This guarantees correct handling of categorical data and enables creation of CPV hierarchy features in the feature engineering stage.

--------------
### Save cleaned datasets

-----------

In [12]:
df_clean.to_pickle("../data/dataset_clean.pkl")
df_de_clean.to_pickle("../data/dataset_de_clean.pkl")