# 02 – Preprocessing & Data Cleaning

### Purpose of the Notebook
This notebook applies systematic cleaning and standardisation to the pre‑saved datasets (dataset.pkl and dataset_de.pkl).
All decisions are based on the insights from Notebook 01_data_overview (EDA), including handling of missing data, removal of low‑quality fields, type corrections, logical consistency checks, and creation of derived features.

### Steps
- Load pre‑saved datasets
- Apply preprocessing pypline
- Save cleaned datasets

--------------------
#### Imports & Setup & Dataset
-------------------

In [3]:
# ---------------------------------------------------------
# Import moduls
# ---------------------------------------------------------


# import standard modules
import pandas as pd
import numpy as np
from pathlib import Path

import sys
from pathlib import Path

In [4]:
# shut off some annoying warnings
import warnings

warnings.filterwarnings("ignore", message="A value is trying to be set on a copy")
warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

In [5]:
# ---------------------------------------------------------
# Setup style
# ---------------------------------------------------------

# show all columns
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# visualisation settings
pd.set_option('display.float_format', '{:,.2f}'.format)

In [6]:
# ---------------------------------------------------------
# Load scripts
# ----------------------------------------------------------

%load_ext autoreload
%autoreload 2

from pathlib import Path
import sys

# found min directory
PROJECT_ROOT = Path("..").resolve()

# maindirectory sys.path
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# import function from script
from my_scripts.preprocessing import preprocess
from my_scripts.eda import overview

In [7]:
# ---------------------------------------------------------
# Import dataset
# ---------------------------------------------------------

df = pd.read_pickle("../data/dataset.pkl")
df_de = pd.read_pickle("../data/dataset_de.pkl")

print("EU dataset:", df.shape)
print("DE dataset:", df_de.shape)

EU dataset: (4039906, 75)
DE dataset: (303349, 75)

--------------
### Apply preprocessing pipeline
-----------

In [8]:
# ---------------------------------------------------------
# full EU dataset
# ---------------------------------------------------------

df_clean = preprocess(df)

In [9]:
# shape of the cleaned EU dataset
print(df_clean.shape)

(4039906, 34)

In [10]:
# inspekt of the cleaned EU dataset
overview(df_clean)

,dtype,total,missing_n,missing_%,uniques_n,uniques
YEAR,int64,4039906,0,0.00,9,"[2008, 2009, 2010, 2011, 2012, 2013, 2014, 201..."
ID_TYPE,int64,4039906,0,0.00,7,"[3, 6, 18, 25, 21, 23, 22]"
DT_DISPATCH,datetime64[us],4039906,0,0.00,3296,"[2007-12-11 00:00:00, 2007-12-27 00:00:00, 200..."
XSD_VERSION,str,4039906,0,0.00,7,"[D205, D206, D207, R207.S3, R208.S1, R208.S2, ..."
CANCELLED,int64,4039906,0,0.00,2,"[0, 1]"
CORRECTIONS,int64,4039906,0,0.00,10,"[0, 1, 2, 3, 5, 4, 84, 7, 8, 6]"
ISO_COUNTRY_CODE,str,4039906,0,0.00,33,"[DE, FR, ES, SE, PL, IT, HU, CY, UK, RO, PT, N..."
CAE_TYPE,str,4039906,0,0.00,10,"[8, 3, 1, 6, R, N, 4, 5A, 5, Z]"
B_AWARDED_BY_CENTRAL_BODY,str,4039906,0,0.00,3,"[Unknown, Y, N]"
TYPE_OF_CONTRACT,str,4039906,0,0.00,3,"[W, U, S]"
TAL_LOCATION_NUTS,str,4039906,0,0.00,9310,"[DED31, DE913, Unknown, DE13A, ES3, FR91, FR52..."
B_DYN_PURCH_SYST,str,4039906,0,0.00,3,"[Unknown, Y, N]"
CPV,str,4039906,0,0.00,10946,"[45215000.0, 45215100.0, 45421145.0, 45234116...."
ID_LOT,str,4039906,0,0.00,3323,"[Unknown, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, Zp 21..."
LOTS_NUMBER,float64,4027577,12329,0.31,373,"[0.0, 3.0, 2.0, 1.0, 4.0, 10.0, 7.0, 13.0, 25...."
VALUE_EURO,float64,2486545,1553361,38.45,628603,"[nan, 5204457.56, 4924202.16, 1400000.0, 88398..."
B_EU_FUNDS,str,4039906,0,0.00,3,"[Unknown, N, Y]"
TOP_TYPE,str,4039906,0,0.00,10,"[OPE, NIC, RES, NOC, COD, Unknown, AWP, NOP, N..."
B_ACCELERATED,str,4039906,0,0.00,2,"[Unknown, Y]"
OUT_OF_DIRECTIVES,int64,4039906,0,0.00,2,"[0, 1]"
CRIT_CODE,str,4039906,0,0.00,3,"[M, L, Unknown]"
CRIT_PRICE_WEIGHT,float64,1631544,2408362,59.61,174,"[nan, 100.0, 70.0, 30.0, 95.0, 85.0, 60.0, 45...."
CRIT_CRITERIA,str,4039906,0,0.00,339917,"[Preis---Qualität, Unknown, Prix---Délai d'int..."
CRIT_WEIGHTS,str,4039906,0,0.00,61524,"[60---40, Unknown, 80---20, 90---10, 70---30, ..."
B_ELECTRONIC_AUCTION,str,4039906,0,0.00,3,"[N, Unknown, Y]"
NUMBER_AWARDS,int64,4039906,0,0.00,484,"[1, 3, 6, 2, 5, 18, 9, 12, 10, 55, 7, 4, 101, ..."
B_AWARDED_TO_A_GROUP,str,4039906,0,0.00,3,"[Unknown, N, Y]"
WIN_COUNTRY_CODE,str,4039906,0,0.00,708,"[DE, FR, Unknown, PL, IT, HU, CY, US, UK, RO, ..."
B_CONTRACTOR_SME,str,4039906,0,0.00,409,"[Unknown, N, Y, N---Y---N---N, N---Y---N, N---..."
TITLE,str,4039906,0,0.00,1317074,"[Unknown, Pakiet Nr 4., Pakiet Nr 5., Pakiet N..."
NUMBER_OFFERS,float64,3521623,518283,12.83,309,"[2.0, 3.0, 1.0, 6.0, 9.0, 5.0, 45.0, 4.0, 10.0..."
AWARD_VALUE_EURO,float64,2538746,1501160,37.16,1529759,"[302964.15, 478780.08, nan, 14237368.1, 492420..."
B_SUBCONTRACTED,str,4039906,0,0.00,3,"[Unknown, N, Y]"
DT_AWARD,datetime64[us],3751143,288763,7.15,4184,"[2007-09-29 00:00:00, 2007-12-21 00:00:00, 200..."

In [11]:
# ---------------------------------------------------------
# Germany
# ---------------------------------------------------------

df_de_clean = preprocess(df_de)

In [12]:
# shape of the cleaned dataset for Germany
print(df_de_clean.shape)

(303349, 34)

In [13]:
# inspekt of the cleaned dataset  for Germany
overview(df_de_clean)

,dtype,total,missing_n,missing_%,uniques_n,uniques
YEAR,int64,303349,0,0.00,9,"[2008, 2009, 2010, 2011, 2012, 2013, 2014, 201..."
ID_TYPE,int64,303349,0,0.00,5,"[3, 6, 18, 25, 21]"
DT_DISPATCH,datetime64[us],303349,0,0.00,2803,"[2007-12-11 00:00:00, 2007-12-27 00:00:00, 200..."
XSD_VERSION,str,303349,0,0.00,7,"[D205, D206, D207, R207.S3, R208.S1, R208.S2, ..."
CANCELLED,int64,303349,0,0.00,2,"[0, 1]"
CORRECTIONS,int64,303349,0,0.00,3,"[0, 1, 2]"
ISO_COUNTRY_CODE,str,303349,0,0.00,1,[DE]
CAE_TYPE,str,303349,0,0.00,10,"[8, 3, 6, N, 1, R, 4, 5A, 5, Z]"
B_AWARDED_BY_CENTRAL_BODY,str,303349,0,0.00,3,"[Unknown, Y, N]"
TYPE_OF_CONTRACT,str,303349,0,0.00,3,"[W, U, S]"
TAL_LOCATION_NUTS,str,303349,0,0.00,2107,"[DED31, DE913, DE13A, DE915, DE712, DEA52, DE9..."
B_DYN_PURCH_SYST,str,303349,0,0.00,3,"[Unknown, Y, N]"
CPV,str,303349,0,0.00,5642,"[45215000.0, 45215100.0, 45233110.0, 45214600...."
ID_LOT,str,303349,0,0.00,448,"[Unknown, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, V2, M..."
LOTS_NUMBER,float64,302602,747,0.25,127,"[0.0, 2.0, 3.0, 7.0, 1.0, 11.0, 4.0, 5.0, 8.0,..."
VALUE_EURO,float64,148929,154420,50.91,87025,"[nan, 5204457.56, 16671.43, 105600.0, 1476658...."
B_EU_FUNDS,str,303349,0,0.00,3,"[Unknown, N, Y]"
TOP_TYPE,str,303349,0,0.00,9,"[OPE, NOC, NIC, RES, Unknown, COD, AWP, NOP, NIP]"
B_ACCELERATED,str,303349,0,0.00,2,"[Unknown, Y]"
OUT_OF_DIRECTIVES,int64,303349,0,0.00,2,"[0, 1]"
CRIT_CODE,str,303349,0,0.00,3,"[M, L, Unknown]"
CRIT_PRICE_WEIGHT,float64,119881,183468,60.48,59,"[nan, 100.0, 70.0, 50.0, 90.0, 40.0, 10.0, 75...."
CRIT_CRITERIA,str,303349,0,0.00,33701,"[Preis---Qualität, Unknown, Preis---Technische..."
CRIT_WEIGHTS,str,303349,0,0.00,9710,"[60---40, Unknown, 90---10, 80---10---10, 1, 5..."
B_ELECTRONIC_AUCTION,str,303349,0,0.00,3,"[N, Unknown, Y]"
NUMBER_AWARDS,int64,303349,0,0.00,159,"[1, 2, 3, 4, 6, 5, 0, 19, 8, 13, 7, 9, 14, 12,..."
B_AWARDED_TO_A_GROUP,str,303349,0,0.00,3,"[Unknown, N, Y]"
WIN_COUNTRY_CODE,str,303349,0,0.00,116,"[DE, Unknown, EE, UK, FR, FI, JO, LB, CH, ES, ..."
B_CONTRACTOR_SME,str,303349,0,0.00,25,"[Unknown, N, Y, Y---Y, N---N---N, N---N, Y---Y..."
TITLE,str,303349,0,0.00,85298,"[Unknown, Neonatologie; Gynäkologie., Echokard..."
NUMBER_OFFERS,float64,257574,45775,15.09,135,"[2.0, 3.0, 9.0, 5.0, 10.0, 19.0, 8.0, nan, 1.0..."
AWARD_VALUE_EURO,float64,144629,158720,52.32,123141,"[302964.15, 478780.08, nan, 478516.22, 129470...."
B_SUBCONTRACTED,str,303349,0,0.00,3,"[Unknown, N, Y]"
DT_AWARD,datetime64[us],275124,28225,9.30,3479,"[2007-09-29 00:00:00, 2007-12-21 00:00:00, 200..."

#### Notes: Summary of Data Cleaning Results

1. Dataset Size After Preprocessing
- Full EU dataset:
  - Before: 4,039,906 rows × 75 columns
  - After: 4,039,906 rows × 34 columns

- Germany-only dataset:
  - Before: 303,349 rows × 75 columns
  - After: 303,349 rows × 34 columns 

2. The reduction from 75 to 34 columns is the result of removing:
- Columns removed due to >40% missing values (with the exception of "TITLE" and "CRIT_CRITERIA", which are important for NLP)
  - Winner information (WIN_*)
  - Contracting authority details (CAE_*)
  - GPA-related fields
  - Secondary financial fields (VALUE_EURO_FIN_*, AWARD_VALUE_EURO_FIN_1)
  - Award criteria weights (CRIT_*)
  - Additional CPVs
  - High-cardinality procedural flags (B_MULTIPLE_, B_FRA_, FRA_ESTIMATED, etc.)
  - TED_NOTICE_URL

- Columns removed due to irrelevance for competition modelling
  - Identifiers (ID_NOTICE_CAN, ID_AWARD, ID_LOT_AWARDED, CONTRACT_NUMBER)
  - Non-award information (INFO_ON_NON_AWARD, INFO_UNPUBLISHED)
  - Administrative metadata (MAIN_ACTIVITY, EU_INST_CODE)

3. Key Variables Retained Despite Missing Values
Several columns with substantial missingness were intentionally retained because they are critical for modelling tender competition and failure risk:
- VALUE_EURO
  - Missing: 39.85% (EU dataset)
  - Missing: 50.28% (Germany)
  - Importance: baseline contract value, used for log-transformations and value bins.

- AWARD_VALUE_EURO
  - Missing: 27.56% (EU dataset)
  - Missing: 43.69% (Germany)
  - Importance: actual awarded value, essential for understanding tender dynamics.

- TITLE
  - Missing: 49.40% (EU dataset)
  - Missing: 43.69% (Germany)
  - Importance: actual awarded value, essential for understanding tender dynamics.

- CRIT_PRICE_WEIGHT, CRIT_CRITERIA, CRIT_WEIGHTS
  - Missing: 60.85%, 54.05%,	56.69% (EU dataset)
  - Missing: 60.09%,	56.07%,	58.14% (Germany)
  - Importance: capture how a tender is evaluated—its balance of price vs. quality, the complexity of requirements, and the structure of scoring—making them essential indicators of competitiveness and failure risk.

These variables were not removed because:
They are central to the analytical goal (competition modelling).
Missingness is informative, not random.

4. Additional Preprocessing Steps
- All categorical missing values were replaced with "Unknown".
- Numeric missing values were left as NaN, to be handled during modelling.

5. Conversion of Categorical Variables
To ensure correct feature engineering and avoid dtype-related errors, all categorical variables were explicitly converted to string (object).
This includes fields such as:
  - ISO_COUNTRY_CODE
  - CAE_TYPE
  - TYPE_OF_CONTRACT
  - TAL_LOCATION_NUTS
  - B_EU_FUNDS
  - TOP_TYPE
  - CRIT_CODE
  - B_ELECTRONIC_AUCTION
  - B_AWARDED_TO_A_GROUP
  - WIN_COUNTRY_CODE
  - B_CONTRACTOR_SME
  - B_SUBCONTRACTED
  - CPV (converted from float → string, with removal of “.0”)
This guarantees correct handling of categorical data and enables creation of CPV hierarchy features in the feature engineering stage.

--------------
### Save cleaned datasets

-----------

In [14]:
df_clean.to_pickle("../data/dataset_clean.pkl")
df_de_clean.to_pickle("../data/dataset_de_clean.pkl")