# 03 – Feature Engineering

### Purpose
This notebook creates engineered features that enhance the predictive power and interpretability of the TED CAN dataset.
All features are based on insights from Notebook 01 (EDA) and domain knowledge of public procurement.

### Steps
- Load cleaned‑saved datasets
- Apply feature engineering pypline
- Save full datasets

--------------------
#### Imports & Setup & Dataset
-------------------

In [1]:
# ---------------------------------------------------------
# Import moduls
# ---------------------------------------------------------


# import standard modules
import pandas as pd
import numpy as np
from pathlib import Path

import sys
from pathlib import Path

In [2]:
# shut off some annoying warnings
import warnings

warnings.filterwarnings("ignore", message="A value is trying to be set on a copy")
warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

In [3]:
# ---------------------------------------------------------
# Setup style
# ---------------------------------------------------------

# show all columns
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# visualisation settings
pd.set_option('display.float_format', '{:,.2f}'.format)

In [4]:
# ---------------------------------------------------------
# Load scripts
# ----------------------------------------------------------

%load_ext autoreload
%autoreload 2

from pathlib import Path
import sys

# found min directory
PROJECT_ROOT = Path("..").resolve()

# maindirectory sys.path
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# import function from script
from my_scripts.feature_engineering import feature_engineering
from my_scripts.eda import overview

In [5]:
# ---------------------------------------------------------
# Import dataset
# ---------------------------------------------------------

df = pd.read_pickle("../data/dataset_clean.pkl")
df_de = pd.read_pickle("../data/dataset_de_clean.pkl")

print("EU dataset:", df.shape)
print("DE dataset:", df_de.shape)

EU dataset: (4039906, 34)
DE dataset: (303349, 34)

---------------------------------------------------------
### Apply feature engineering

-----------------------------

In [6]:
# ---------------------------------------------------------
# full EU dataset
# ---------------------------------------------------------

df_fe = feature_engineering(df)

In [7]:
# shape of the EU dataset
print(df_fe.shape)

(4039906, 43)

In [8]:
# inspekt of the EU dataset
overview(df_fe)

,dtype,total,missing_n,missing_%,uniques_n,uniques
YEAR,int64,4039906,0,0.00,9,"[2008, 2009, 2010, 2011, 2012, 2013, 2014, 201..."
ID_TYPE,int64,4039906,0,0.00,7,"[3, 6, 18, 25, 21, 23, 22]"
XSD_VERSION,str,4039906,0,0.00,7,"[D205, D206, D207, R207.S3, R208.S1, R208.S2, ..."
CANCELLED,int64,4039906,0,0.00,2,"[0, 1]"
CORRECTIONS,int64,4039906,0,0.00,10,"[0, 1, 2, 3, 5, 4, 84, 7, 8, 6]"
ISO_COUNTRY_CODE,str,4039906,0,0.00,33,"[DE, FR, ES, SE, PL, IT, HU, CY, UK, RO, PT, N..."
CAE_TYPE,str,4039906,0,0.00,10,"[8, 3, 1, 6, R, N, 4, 5A, 5, Z]"
B_AWARDED_BY_CENTRAL_BODY,str,4039906,0,0.00,3,"[Unknown, Y, N]"
TYPE_OF_CONTRACT,str,4039906,0,0.00,3,"[W, U, S]"
TAL_LOCATION_NUTS,str,4039906,0,0.00,9310,"[DED31, DE913, Unknown, DE13A, ES3, FR91, FR52..."
B_DYN_PURCH_SYST,int64,4039906,0,0.00,2,"[0, 1]"
ID_LOT,str,4039906,0,0.00,3323,"[Unknown, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, Zp 21..."
B_EU_FUNDS,str,4039906,0,0.00,3,"[Unknown, N, Y]"
TOP_TYPE,str,4039906,0,0.00,10,"[OPE, NIC, RES, NOC, COD, Unknown, AWP, NOP, N..."
B_ACCELERATED,int64,4039906,0,0.00,2,"[0, 1]"
OUT_OF_DIRECTIVES,int64,4039906,0,0.00,2,"[0, 1]"
CRIT_CODE,str,4039906,0,0.00,3,"[M, L, Unknown]"
CRIT_PRICE_WEIGHT,float64,1631544,2408362,59.61,174,"[nan, 100.0, 70.0, 30.0, 95.0, 85.0, 60.0, 45...."
CRIT_CRITERIA,str,4039906,0,0.00,339917,"[Preis---Qualität, Unknown, Prix---Délai d'int..."
CRIT_WEIGHTS,str,4039906,0,0.00,61524,"[60---40, Unknown, 80---20, 90---10, 70---30, ..."
B_ELECTRONIC_AUCTION,int64,4039906,0,0.00,2,"[0, 1]"
NUMBER_AWARDS,int64,4039906,0,0.00,484,"[1, 3, 6, 2, 5, 18, 9, 12, 10, 55, 7, 4, 101, ..."
B_AWARDED_TO_A_GROUP,int64,4039906,0,0.00,2,"[0, 1]"
WIN_COUNTRY_CODE,str,4039906,0,0.00,708,"[DE, FR, Unknown, PL, IT, HU, CY, US, UK, RO, ..."
B_CONTRACTOR_SME,int64,4039906,0,0.00,2,"[0, 1]"
TITLE,str,4039906,0,0.00,1317074,"[Unknown, Pakiet Nr 4., Pakiet Nr 5., Pakiet N..."
B_SUBCONTRACTED,str,4039906,0,0.00,3,"[Unknown, N, Y]"
AWARD_YEAR,float64,3751143,288763,7.15,30,"[2007.0, nan, 2006.0, 2008.0, 2012.0, 2005.0, ..."
AWARD_MONTH,float64,3751143,288763,7.15,12,"[9.0, 12.0, 11.0, 10.0, nan, 8.0, 3.0, 7.0, 1...."
AWARD_QUARTER,float64,3751143,288763,7.15,4,"[3.0, 4.0, nan, 1.0, 2.0]"
DAYS_TO_AWARD,float64,3751143,288763,7.15,2150,"[-73.0, -6.0, -37.0, -63.0, -27.0, nan, -14.0,..."
CPV_DIVISION,str,4039906,0,0.00,69,"[45, 60, 24, 50, 93, Un, 28, 32, 34, 33, 23, 1..."
CPV_GROUP,str,4039906,0,0.00,470,"[452, 454, 601, 240, 502, 450, 935, 453, Unk, ..."
CPV_CLASS,str,4039906,0,0.00,1836,"[4521, 4542, 4523, 6012, 2400, 4524, 5024, 450..."
IS_FAILED_TENDER,int64,4039906,0,0.00,2,"[0, 1]"
IS_LOW_COMPETITION,int64,4039906,0,0.00,2,"[1, 0]"
OFFERS_BIN,category,3521619,518287,12.83,4,"['low', 'medium', 'failed', 'high', NaN] Categ..."
VALUE_BIN,category,2486545,1553361,38.45,5,"[NaN, 'large', 'mega', 'small', 'medium', 'mic..."
HAS_MULTIPLE_LOTS,int64,4039906,0,0.00,2,"[0, 1]"
LOTS_BIN,category,4027577,12329,0.31,4,"['single', 'few', 'many', 'mega', NaN] Categor..."
VALUE_EURO_MISSING,int64,4039906,0,0.00,2,"[1, 0]"
AWARD_VALUE_EURO_MISSING,int64,4039906,0,0.00,2,"[0, 1]"
NUMBER_OFFERS_MISSING,int64,4039906,0,0.00,2,"[0, 1]"

In [9]:
# ---------------------------------------------------------
# dataset for Germany
# ---------------------------------------------------------

df_de_fe = feature_engineering(df_de)

In [10]:
# shape of the EU dataset
print(df_de_fe.shape)

(303349, 43)

In [11]:
# inspekt of the EU dataset
overview(df_de_fe)

,dtype,total,missing_n,missing_%,uniques_n,uniques
YEAR,int64,303349,0,0.00,9,"[2008, 2009, 2010, 2011, 2012, 2013, 2014, 201..."
ID_TYPE,int64,303349,0,0.00,5,"[3, 6, 18, 25, 21]"
XSD_VERSION,str,303349,0,0.00,7,"[D205, D206, D207, R207.S3, R208.S1, R208.S2, ..."
CANCELLED,int64,303349,0,0.00,2,"[0, 1]"
CORRECTIONS,int64,303349,0,0.00,3,"[0, 1, 2]"
ISO_COUNTRY_CODE,str,303349,0,0.00,1,[DE]
CAE_TYPE,str,303349,0,0.00,10,"[8, 3, 6, N, 1, R, 4, 5A, 5, Z]"
B_AWARDED_BY_CENTRAL_BODY,str,303349,0,0.00,3,"[Unknown, Y, N]"
TYPE_OF_CONTRACT,str,303349,0,0.00,3,"[W, U, S]"
TAL_LOCATION_NUTS,str,303349,0,0.00,2107,"[DED31, DE913, DE13A, DE915, DE712, DEA52, DE9..."
B_DYN_PURCH_SYST,int64,303349,0,0.00,2,"[0, 1]"
ID_LOT,str,303349,0,0.00,448,"[Unknown, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, V2, M..."
B_EU_FUNDS,str,303349,0,0.00,3,"[Unknown, N, Y]"
TOP_TYPE,str,303349,0,0.00,9,"[OPE, NOC, NIC, RES, Unknown, COD, AWP, NOP, NIP]"
B_ACCELERATED,int64,303349,0,0.00,2,"[0, 1]"
OUT_OF_DIRECTIVES,int64,303349,0,0.00,2,"[0, 1]"
CRIT_CODE,str,303349,0,0.00,3,"[M, L, Unknown]"
CRIT_PRICE_WEIGHT,float64,119881,183468,60.48,59,"[nan, 100.0, 70.0, 50.0, 90.0, 40.0, 10.0, 75...."
CRIT_CRITERIA,str,303349,0,0.00,33701,"[Preis---Qualität, Unknown, Preis---Technische..."
CRIT_WEIGHTS,str,303349,0,0.00,9710,"[60---40, Unknown, 90---10, 80---10---10, 1, 5..."
B_ELECTRONIC_AUCTION,int64,303349,0,0.00,2,"[0, 1]"
NUMBER_AWARDS,int64,303349,0,0.00,159,"[1, 2, 3, 4, 6, 5, 0, 19, 8, 13, 7, 9, 14, 12,..."
B_AWARDED_TO_A_GROUP,int64,303349,0,0.00,2,"[0, 1]"
WIN_COUNTRY_CODE,str,303349,0,0.00,116,"[DE, Unknown, EE, UK, FR, FI, JO, LB, CH, ES, ..."
B_CONTRACTOR_SME,int64,303349,0,0.00,2,"[0, 1]"
TITLE,str,303349,0,0.00,85298,"[Unknown, Neonatologie; Gynäkologie., Echokard..."
B_SUBCONTRACTED,str,303349,0,0.00,3,"[Unknown, N, Y]"
AWARD_YEAR,float64,275124,28225,9.30,23,"[2007.0, nan, 2008.0, 2006.0, 2005.0, 2000.0, ..."
AWARD_MONTH,float64,275124,28225,9.30,12,"[9.0, 12.0, 11.0, nan, 1.0, 10.0, 3.0, 8.0, 4...."
AWARD_QUARTER,float64,275124,28225,9.30,4,"[3.0, 4.0, nan, 1.0, 2.0]"
DAYS_TO_AWARD,float64,275124,28225,9.30,993,"[-73.0, -6.0, -27.0, -23.0, -14.0, -43.0, -45...."
CPV_DIVISION,str,303349,0,0.00,67,"[45, 30, 40, 34, Un, 36, 14, 78, 50, 74, 18, 2..."
CPV_GROUP,str,303349,0,0.00,405,"[452, 453, 302, 401, 341, Unk, 361, 144, 782, ..."
CPV_CLASS,str,303349,0,0.00,1349,"[4521, 4523, 4534, 3023, 4010, 3411, Unkn, 302..."
IS_FAILED_TENDER,int64,303349,0,0.00,2,"[0, 1]"
IS_LOW_COMPETITION,int64,303349,0,0.00,2,"[1, 0]"
OFFERS_BIN,category,257574,45775,15.09,4,"['low', 'medium', 'high', NaN, 'failed'] Categ..."
VALUE_BIN,category,148929,154420,50.91,5,"[NaN, 'large', 'small', 'medium', 'mega', 'mic..."
HAS_MULTIPLE_LOTS,int64,303349,0,0.00,2,"[0, 1]"
LOTS_BIN,category,302602,747,0.25,4,"['single', 'few', 'many', 'mega', NaN] Categor..."
VALUE_EURO_MISSING,int64,303349,0,0.00,2,"[1, 0]"
AWARD_VALUE_EURO_MISSING,int64,303349,0,0.00,2,"[0, 1]"
NUMBER_OFFERS_MISSING,int64,303349,0,0.00,2,"[0, 1]"

#### Notes: Feature Engineering Summary
Feature engineering enriches the cleaned dataset with additional analytical variables that improve modelling of tender competition, risk, and procedural behaviour.

1. Dataset Size After Features Engineering
- Full EU dataset:
  - Before: 4,039,906 rows × 34 columns
  - After: 4,039,906 rows × 43 columns

- Germany-only dataset:
  - Before: 303,349 rows × 34 columns
  - After: 303,349 rows × 43 columns

2. Created Features
- Date‑based features
  - AWARD_YEAR
  - AWARD_MONTH
  - AWARD_QUARTER
  - DAYS_TO_AWARD (time between dispatch and award)
These variables capture temporal patterns, seasonality, and procedural duration.

- CPV hierarchy features
  - CPV_DIVISION (first 2 digits)
  - CPV_GROUP (first 3 digits)
  - CPV_CLASS (first 4 digits)
The CPV field was converted from float to string and cleaned (removal of “.0”) to enable correct hierarchical extraction.

- Competition features
  - IS_FAILED_TENDER (≤1 offer)
  - IS_LOW_COMPETITION (=2 offers)
  - OFFERS_BIN (failed / low / medium / high)
These features form the basis for competition and risk modelling.

- Value‑based features
  - VALUE_BIN (micro / small / medium / large / mega)
This categorisation helps the model handle highly skewed contract value distributions.

- Tender complexity features
  - HAS_MULTIPLE_LOTS
  - LOTS_BIN (single / few / many / mega)
These variables reflect structural complexity of the tender.

- Boolean indicators (Y/N into 1/0)
  - B_ELECTRONIC_AUCTION
  - B_DYN_PURCH_SYST
  - B_ACCELERATED
  - B_AWARDED_TO_A_GROUP
  - B_CONTRACTOR_SME
All Y/N fields were mapped to binary numeric format.

- Missing‑information flags
  - VALUE_EURO_MISSING
  - AWARD_VALUE_EURO_MISSING
  - NUMBER_OFFERS_MISSING
These indicators allow the model to capture informative missingness.

3. Removed Raw Columns
After generating engineered features, the following original fields were dropped to avoid redundancy:
  - CPV
  - DT_AWARD, DT_DISPATCH
  - VALUE_EURO, AWARD_VALUE_EURO, AWARD_EST_VALUE_EURO
  - LOTS_NUMBER
  - NUMBER_OFFERS

------------------
### Save engineered datasets

-------------------

In [12]:
df_fe.to_pickle("../data/dataset_fe.pkl")
df_de_fe.to_pickle("../data/dataset_de_fe.pkl")